[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["HoNile <nicolas_cohen@hotmail.fr>"]
edition = "2018"

[dependencies]
rayon = "1.5"
image = "0.21.2"

[profile.release]
codegen-units = 1
lto = true